# Jekyll Resume Theme

# Site settings
title: Tomás Vich Cólogan
email: tvcologan@gmail.com
description: Tomás Vich Cólogan - Resume
baseurl:
url: "https://tvcologan.com/resume"
name: Tomás Vich Cólogan
job: software engineer
location: Canary Islands, Spain (Atlantic/Canary)
languages:
twitter_username:
github_username:
codepen_username:
linkedin_username: tomas-vich-cologan-6b0a73140
email_address: tvcologan@gmail.com

# Build settings
markdown: kramdown
